version: "3"

tasks:
  format-web:
    internal: true
    dir: web
    cmds:
      - pnpm run format
    desc: "Formatting /web with prettier"

  format-api:
    internal: true
    dir: api
    cmds:
      - uv run ruff format 
    desc: "Formatting /api with ruff"

  format-pipeline:
    internal: true
    dir: pipeline
    cmds:
      - uv run ruff format
    desc: "Formatting /pipeline with ruff"

  format:
    deps:
      - format-web
      - format-api
      - format-pipeline
    desc: "Formatting all the code"

  start-web:
    internal: true
    dir: web
    cmds:
      - pnpm run dev
    desc: "Starting the web server"

  start-api:
    internal: true
    dir: api
    cmds:
      - uv run fastapi dev app.py
    desc: "Starting the API server"

  start:
    deps:
      - start-web
      # - start-api
    desc: "Starting the web and API servers"
