[project]
name = "ira"
version = "0.1.0"
description = "Ira, one lyric at a time"
author = "Manas Pratim Biswas <manaspb2405@gmail.com>"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
